/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorSimRouteImport } from './routes/vendor-sim'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PeopleHubFeedRouteImport } from './routes/people-hub-feed'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications-settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as ConversionRouteImport } from './routes/conversion'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BackgroundChecksRouteImport } from './routes/background-checks'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequisitionsIndexRouteImport } from './routes/requisitions.index'
import { Route as PipelineIndexRouteImport } from './routes/pipeline.index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as RequisitionsIdRouteImport } from './routes/requisitions.$id'
import { Route as PipelineReqIdRouteImport } from './routes/pipeline.$reqId'
import { Route as CandidatesIdRouteImport } from './routes/candidates.$id'
import { Route as CandidatesIdScorecardRouteImport } from './routes/candidates.$id.scorecard'
import { Route as ApiPublicTalentDotoutcomeDotv1RouteImport } from './routes/api.public.talent[.]outcome[.]v1'
import { Route as ApiPublicAiGenerateJdRouteImport } from './routes/api.public.ai.generate-jd'

const VendorSimRoute = VendorSimRouteImport.update({
  id: '/vendor-sim',
  path: '/vendor-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleHubFeedRoute = PeopleHubFeedRouteImport.update({
  id: '/people-hub-feed',
  path: '/people-hub-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/notifications-settings',
  path: '/notifications-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionRoute = ConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundChecksRoute = BackgroundChecksRouteImport.update({
  id: '/background-checks',
  path: '/background-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsIndexRoute = RequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsIdRoute = RequisitionsIdRouteImport.update({
  id: '/requisitions/$id',
  path: '/requisitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineReqIdRoute = PipelineReqIdRouteImport.update({
  id: '/pipeline/$reqId',
  path: '/pipeline/$reqId',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdScorecardRoute = CandidatesIdScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => CandidatesIdRoute,
} as any)
const ApiPublicTalentDotoutcomeDotv1Route =
  ApiPublicTalentDotoutcomeDotv1RouteImport.update({
    id: '/api/public/talent.outcome.v1',
    path: '/api/public/talent.outcome.v1',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiGenerateJdRoute = ApiPublicAiGenerateJdRouteImport.update({
  id: '/api/public/ai/generate-jd',
  path: '/api/public/ai/generate-jd',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/background-checks': typeof BackgroundChecksRoute
  '/careers': typeof CareersRoute
  '/conversion': typeof ConversionRoute
  '/forecasts': typeof ForecastsRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/notifications-settings': typeof NotificationsSettingsRoute
  '/offers': typeof OffersRoute
  '/people-hub-feed': typeof PeopleHubFeedRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/vendor-sim': typeof VendorSimRoute
  '/candidates/$id': typeof CandidatesIdRouteWithChildren
  '/pipeline/$reqId': typeof PipelineReqIdRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/requisitions/': typeof RequisitionsIndexRoute
  '/api/public/talent.outcome.v1': typeof ApiPublicTalentDotoutcomeDotv1Route
  '/candidates/$id/scorecard': typeof CandidatesIdScorecardRoute
  '/api/public/ai/generate-jd': typeof ApiPublicAiGenerateJdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/background-checks': typeof BackgroundChecksRoute
  '/careers': typeof CareersRoute
  '/conversion': typeof ConversionRoute
  '/forecasts': typeof ForecastsRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/notifications-settings': typeof NotificationsSettingsRoute
  '/offers': typeof OffersRoute
  '/people-hub-feed': typeof PeopleHubFeedRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/vendor-sim': typeof VendorSimRoute
  '/candidates/$id': typeof CandidatesIdRouteWithChildren
  '/pipeline/$reqId': typeof PipelineReqIdRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/candidates': typeof CandidatesIndexRoute
  '/pipeline': typeof PipelineIndexRoute
  '/requisitions': typeof RequisitionsIndexRoute
  '/api/public/talent.outcome.v1': typeof ApiPublicTalentDotoutcomeDotv1Route
  '/candidates/$id/scorecard': typeof CandidatesIdScorecardRoute
  '/api/public/ai/generate-jd': typeof ApiPublicAiGenerateJdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/background-checks': typeof BackgroundChecksRoute
  '/careers': typeof CareersRoute
  '/conversion': typeof ConversionRoute
  '/forecasts': typeof ForecastsRoute
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/notifications-settings': typeof NotificationsSettingsRoute
  '/offers': typeof OffersRoute
  '/people-hub-feed': typeof PeopleHubFeedRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/vendor-sim': typeof VendorSimRoute
  '/candidates/$id': typeof CandidatesIdRouteWithChildren
  '/pipeline/$reqId': typeof PipelineReqIdRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/requisitions/': typeof RequisitionsIndexRoute
  '/api/public/talent.outcome.v1': typeof ApiPublicTalentDotoutcomeDotv1Route
  '/candidates/$id/scorecard': typeof CandidatesIdScorecardRoute
  '/api/public/ai/generate-jd': typeof ApiPublicAiGenerateJdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/analytics'
    | '/announcements'
    | '/audit'
    | '/background-checks'
    | '/careers'
    | '/conversion'
    | '/forecasts'
    | '/interviews'
    | '/login'
    | '/notifications'
    | '/notifications-settings'
    | '/offers'
    | '/people-hub-feed'
    | '/referrals'
    | '/settings'
    | '/showcase'
    | '/vendor-sim'
    | '/candidates/$id'
    | '/pipeline/$reqId'
    | '/requisitions/$id'
    | '/candidates/'
    | '/pipeline/'
    | '/requisitions/'
    | '/api/public/talent.outcome.v1'
    | '/candidates/$id/scorecard'
    | '/api/public/ai/generate-jd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencies'
    | '/analytics'
    | '/announcements'
    | '/audit'
    | '/background-checks'
    | '/careers'
    | '/conversion'
    | '/forecasts'
    | '/interviews'
    | '/login'
    | '/notifications'
    | '/notifications-settings'
    | '/offers'
    | '/people-hub-feed'
    | '/referrals'
    | '/settings'
    | '/showcase'
    | '/vendor-sim'
    | '/candidates/$id'
    | '/pipeline/$reqId'
    | '/requisitions/$id'
    | '/candidates'
    | '/pipeline'
    | '/requisitions'
    | '/api/public/talent.outcome.v1'
    | '/candidates/$id/scorecard'
    | '/api/public/ai/generate-jd'
  id:
    | '__root__'
    | '/'
    | '/agencies'
    | '/analytics'
    | '/announcements'
    | '/audit'
    | '/background-checks'
    | '/careers'
    | '/conversion'
    | '/forecasts'
    | '/interviews'
    | '/login'
    | '/notifications'
    | '/notifications-settings'
    | '/offers'
    | '/people-hub-feed'
    | '/referrals'
    | '/settings'
    | '/showcase'
    | '/vendor-sim'
    | '/candidates/$id'
    | '/pipeline/$reqId'
    | '/requisitions/$id'
    | '/candidates/'
    | '/pipeline/'
    | '/requisitions/'
    | '/api/public/talent.outcome.v1'
    | '/candidates/$id/scorecard'
    | '/api/public/ai/generate-jd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciesRoute: typeof AgenciesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuditRoute: typeof AuditRoute
  BackgroundChecksRoute: typeof BackgroundChecksRoute
  CareersRoute: typeof CareersRoute
  ConversionRoute: typeof ConversionRoute
  ForecastsRoute: typeof ForecastsRoute
  InterviewsRoute: typeof InterviewsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  OffersRoute: typeof OffersRoute
  PeopleHubFeedRoute: typeof PeopleHubFeedRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  ShowcaseRoute: typeof ShowcaseRoute
  VendorSimRoute: typeof VendorSimRoute
  CandidatesIdRoute: typeof CandidatesIdRouteWithChildren
  PipelineReqIdRoute: typeof PipelineReqIdRoute
  RequisitionsIdRoute: typeof RequisitionsIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
  RequisitionsIndexRoute: typeof RequisitionsIndexRoute
  ApiPublicTalentDotoutcomeDotv1Route: typeof ApiPublicTalentDotoutcomeDotv1Route
  ApiPublicAiGenerateJdRoute: typeof ApiPublicAiGenerateJdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor-sim': {
      id: '/vendor-sim'
      path: '/vendor-sim'
      fullPath: '/vendor-sim'
      preLoaderRoute: typeof VendorSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people-hub-feed': {
      id: '/people-hub-feed'
      path: '/people-hub-feed'
      fullPath: '/people-hub-feed'
      preLoaderRoute: typeof PeopleHubFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications-settings': {
      id: '/notifications-settings'
      path: '/notifications-settings'
      fullPath: '/notifications-settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion': {
      id: '/conversion'
      path: '/conversion'
      fullPath: '/conversion'
      preLoaderRoute: typeof ConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-checks': {
      id: '/background-checks'
      path: '/background-checks'
      fullPath: '/background-checks'
      preLoaderRoute: typeof BackgroundChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/': {
      id: '/requisitions/'
      path: '/requisitions'
      fullPath: '/requisitions/'
      preLoaderRoute: typeof RequisitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/$id': {
      id: '/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/requisitions/$id'
      preLoaderRoute: typeof RequisitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/$reqId': {
      id: '/pipeline/$reqId'
      path: '/pipeline/$reqId'
      fullPath: '/pipeline/$reqId'
      preLoaderRoute: typeof PipelineReqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id/scorecard': {
      id: '/candidates/$id/scorecard'
      path: '/scorecard'
      fullPath: '/candidates/$id/scorecard'
      preLoaderRoute: typeof CandidatesIdScorecardRouteImport
      parentRoute: typeof CandidatesIdRoute
    }
    '/api/public/talent.outcome.v1': {
      id: '/api/public/talent.outcome.v1'
      path: '/api/public/talent.outcome.v1'
      fullPath: '/api/public/talent.outcome.v1'
      preLoaderRoute: typeof ApiPublicTalentDotoutcomeDotv1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/generate-jd': {
      id: '/api/public/ai/generate-jd'
      path: '/api/public/ai/generate-jd'
      fullPath: '/api/public/ai/generate-jd'
      preLoaderRoute: typeof ApiPublicAiGenerateJdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CandidatesIdRouteChildren {
  CandidatesIdScorecardRoute: typeof CandidatesIdScorecardRoute
}

const CandidatesIdRouteChildren: CandidatesIdRouteChildren = {
  CandidatesIdScorecardRoute: CandidatesIdScorecardRoute,
}

const CandidatesIdRouteWithChildren = CandidatesIdRoute._addFileChildren(
  CandidatesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciesRoute: AgenciesRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuditRoute: AuditRoute,
  BackgroundChecksRoute: BackgroundChecksRoute,
  CareersRoute: CareersRoute,
  ConversionRoute: ConversionRoute,
  ForecastsRoute: ForecastsRoute,
  InterviewsRoute: InterviewsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  OffersRoute: OffersRoute,
  PeopleHubFeedRoute: PeopleHubFeedRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  ShowcaseRoute: ShowcaseRoute,
  VendorSimRoute: VendorSimRoute,
  CandidatesIdRoute: CandidatesIdRouteWithChildren,
  PipelineReqIdRoute: PipelineReqIdRoute,
  RequisitionsIdRoute: RequisitionsIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  PipelineIndexRoute: PipelineIndexRoute,
  RequisitionsIndexRoute: RequisitionsIndexRoute,
  ApiPublicTalentDotoutcomeDotv1Route: ApiPublicTalentDotoutcomeDotv1Route,
  ApiPublicAiGenerateJdRoute: ApiPublicAiGenerateJdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
